[project]
name = "generate-synthetic-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.2.26",
    "langchain-openai>=0.1.17",
    "langgraph>=0.1.9",
]
